import Footer from "@/components/footer";
import NavBar from "@/components/nav-bar";
import Providers from "@/components/providers";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import { Recursive } from 'next/font/google';
import "./globals.css";

const recursive = Recursive({
  subsets: ['latin'],
  display: "swap"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${recursive}`}>
        <NavBar />
        <main className="grainy-light flex flex-col min-h-[calc(100vh-3.5rem-1px)]">
          <div className="flex-1 flex flex-col h-full">
            <Providers>
              {children}
            </Providers>
            <Footer />
          </div>

        </main>

        <Toaster />
      </body>
    </html>
  );
}
